sudo: required

language: bash

services:
  - docker

script:
  - docker build -t android-sdk ./android-sdk
  - docker images
  - cmd=$(cat ./version_inspector.sh) && docker run -it --rm android-sdk bash -c "$cmd"
