sudo: required

language: bash

services:
  - docker

script:
  - docker build -t android-sdk ~/AndroidSDK/android-sdk
  - docker build -t android-sdk-firebase-test-lab ~/AndroidSDK/android-sdk/firebase-test-lab
  - docker images
  - cmd=$(cat ./version_inspector.sh) && docker run -it --rm android-sdk bash -c "$cmd"
  - cmd=$(cat android-sdk/firebase-test-lab/version_inspector.sh) && docker run -it --rm android-sdk-firebase-test-lab bash -c "$cmd"

