sudo: required

language: bash

services:
  - docker

install:
  - git clone https://github.com/thyrlian/AndroidSDK.git ~/AndroidSDK

script:
  - docker build -t android-sdk ~/AndroidSDK/android-sdk
  - docker images
  - docker run -d android-sdk
  - docker exec -it `docker ps -aqf "ancestor=android-sdk"` bash -c 'java -version && gradle -v && sdkmanager --list'
