sudo: required

language: bash

services:
  - docker

install:
  - git clone https://github.com/thyrlian/AndroidSDK ~/AndroidSDK

script:
  - docker build -t android-sdk ~/AndroidSDK/android-sdk
  - docker images
  - echo "$ANDROID_HOME/tools/bin/sdkmanager --list" | docker run -i android-sdk
